---
- hosts: all
  become: yes
  tasks:
  - name: "installing apache on ubuntu"
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: "installing apache on Centos"
    yum: 
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: "starting apache on Centos"
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"