---
- hosts: all
  become: yes
  tasks:
  - name: "installing git"
    apt:
      name: git
      state: present
    when: ansible_os_family == "Debian"
  - name: "installing git on centos"
    yum:
      name: git
      state: present
    when: ansible_os_family == "RedHat"